import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <h1 className="text-3xl text-violet-600 text-center font-mono font-bold">
          NextJS 13, Typescript and Tailwind Starter
        </h1>
      </main>
    </>
  );
}
